# Generated by Django 4.2.5 on 2023-09-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredientes', models.CharField(max_length=400)),
                ('precio_p', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precio_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precio_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('existencia', models.SmallIntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('cat_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.categoriaproducto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.proveedor')),
            ],
        ),
    ]
