# Generated by Django 4.2.5 on 2023-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_productointerno_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='productointerno',
            name='foto',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
